name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: zenstruck/.github@php-test-symfony
        with:
          php: 8.2

  cs:
    uses: zenstruck/.github/.github/workflows/php-cs-fixer.yml@main
    with:
      php: 8.2

  sca:
    uses: zenstruck/.github/.github/workflows/php-stan.yml@main
    with:
      php: 8.2
